server:
  port: 9999
  address: localhost
  servlet:
    context-path: /service-taskman
spring:
  profiles:
    active: dev
  messages:
    basename: message/service_mgmt_err_message
    encoding: UTF-8
  banner:
    location: classpath:/banner.txt

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1



logging:
  level:
    root: info