server:
  port: 9999
  servlet:
    context-path: /taskman
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_host}:${db_port}/${db_schema}?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${db_username}
    password: ${db_password}
  messages:
    basename: message/service_mgmt_err_message
    encoding: UTF-8
  banner:
    location: classpath:/banner.txt
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write_numbers_as_strings: true
    serialization:
      indent_output: true
      fail_on_empty_beans: false
      #defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
      #property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES﻿
mybatis-plus:
  mapper-locations: mapper/*.xml
  global-config:
    banner: false
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1

#分页插件
pagehelper:
  helperDialect: mysql
  paramsCount: countSql
  reasonable: true
  supportMethodsArguments: true

knife4j:
  enable: true
  setting:
    enableVersion: true
    enableSwaggerModels: false
    enableDocumentManage: false
    enableReloadCacheParameter: true
    enableAfterScript: true
    enableRequestCache: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright © 2014 - 2019 WeBank Co., Ltd. All Rights Reserved.
    enableDynamicParameter: true
    enableDebug: true
    enableOpenApi: false
    enableGroup: false
  production: false # prod close knife4j
  basic:
    enable: false
    username: test
    password: 12313

service:
  taskman:
    httpclient:
      max-total-connections: 200
    wecube-core-address: ${core_addr}
    wecube-platform-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIVFRQLU1PQ0siLCJpYXQiOjE1NzYwNTMxOTcsInR5cGUiOiJhY2Nlc3NUb2tlbiIsImNsaWVudFR5cGUiOiJTVUJfU1lTVEVNIiwiZXhwIjoxNjAxOTczMTk3LCJhdXRob3JpdHkiOiJbU1VCX1NZU1RFTV0ifQ.Wd5rhFX3G-dtqlqYzgnkzd9i8T0xJkkPQSAckzO3V3NWXMCw3B9JWe7JlMjbNtE7va8qce1qcrz6qaa4pB0t5A
    s3-endpoint: ${s3_endpoint}
    s3-access-key: ${s3_access_key}
    s3-secret-key: ${s3_secret_key}
    s3-default-bucket: service-taskman
    system-code: SYS_SRV_MGMT
    jwt-signing-key: ${JWT_SIGNING_KEY:}
    property-encrypt-key-path: ${PROPERTY_ENCRYPT_KEY_PATH:/data/certs/rsa_key}
    aspect-log-controller: true
    aspect-log-controller-printResult: true

logging:
  level:
    root: info
    com.webank.taskman.mapper: debug
    com.zaxxer.hikari.HikariDataSource: ERROR
    org.springframework.web.servlet: WARN
    org.springframework.security.web: WARN
    #org.springframework.boot.web: WARN
    org.apache.catalina.core: WARN
    com.ulisesbocchio.jasyptspringboot: WARN
    springfox.documentation.spring.web: WARN