server:
  port: 9999
  address: localhost
  servlet:
    context-path: /service-taskman
spring:
  profiles:
    active: dev
  messages:
    basename: message/service_mgmt_err_message
    encoding: UTF-8
  banner:
    location: classpath:/banner.txt

mybatis-plus:
  mapper-locations: mapper/*.xml

logging:
  level:
    root: info