server:
  port: 9999
  servlet:
    context-path: /taskman
spring:
  profiles:
    active: dev
  messages:
    basename: message/service_mgmt_err_message
    encoding: UTF-8
  banner:
    location: classpath:/banner.txt

mybatis-plus:
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1



logging:
  level:
    root: info