server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.160.142:13307/taskman?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Abcd1234