spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskman?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root